resourcestring                                     {english}

//  gmapURL='https://maps.google.com/maps';

  capApplication='GPS log tool';
  capSatSNR='Signal to noise ratio';
  hntSatSNR='Signal to noise ratio of satellite  [dB]';
  capData='Positioning data';
  hntData='Positioning data from message GPS_RAW_INT';
  capPolar='Azimuth and elevation of visible sats';
  hntPolar='Azimuth: Direction of satellite 0 to 360°, Elevation: 0 to 90° (0°: right on top of receiver, 90°: on the horizon)';
  capClose='&Close';
  hntClose='Quit and close the application';
  capLoadFile='&Open file';
  hntLoadFile='Open and process TLOG or H480 Sensor file. File format will be detected by the application.';
  hntStatusBar='Messages checked; Messages used; File name';
  capOpenDialog='Open TLOG or H480 Sensor file...';
  capTime='Time';
  hntTime='Date/time UTC from message SYSTEM_TIME (2)';
  capSaveCSV='Save as CSV file';
  hntSaveCSV='Automatically save GPS data as CSV file in the same folder as the input files are';
  capFast='Fast processing w/o GUI update';
  hntFast='Fast processing without update GUI but creates CSV data. Automatic save should be checked.';
  hntSleepTime='Set delay in ms (0..1000), default: 100';
  capSaveGrid='Save data table';
  hntSaveGrid='Save snapshot of the current values in the data table';
  capSaveChart='Save chart';
  hntSaveChart='Save snapshot of the diagram as picture';
  capAbout='About';

  capMainMenuFile='File';
  capMainMenuInfo='Info';

  errInvalidFile='Invalid file';
  errSmallFile='File too small';
  errEmptyFile='File is empty, nothing saved';
  errSensorsNotHealthy='Sensors not healthy!';

  rsInUse='satellites in use';
  rsVisible='satellites visible';
  rsSaved='saved in working directory';
  rsGPSmissing='Compass and/or GPS not present!';


